apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
        - name: test-job
          image: gcr.io/project_id/image_name:tag
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-k80

